GET http://localhost:5000/user

###
GET http://localhost:5000/user/66a756ec66c61d26cbc0455e


###
POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "bujang",
    "email": "didinzakaria123@gmail.com",
    "gender": "male",
    "password": "didin"
}

###
PATCH  http://localhost:5000/user/6686ddc4631cb0d9e87c08d9
Content-Type: application/json

{
    "name": "juragan",
    "email": "juragan@gmail.com",
    "gender": "female"
}

###
DELETE http://localhost:5000/user/delete/66a756ec66c61d26cbc0455e

###
Post http://localhost:5000/login
Content-Type: application/json

{
    "email": "didinzakaria123@gmail.com",
    "password": "admin"
}
